### ISSUE TITLE
openwbmqtt + solaredge modbus

### ISSUE THREAD

**Issue by ChristophCaina** [a529987659852/openwbmqtt#25]
Hi,
I am running a SolarEdge inverter, which was connected to my homeassistant per Modbus, to collect some real-time production information and the inverter status.

After the installation of my openWB, the inverter is now communicating directly with the openWB - and I can't run the SolarEdge Modbus communication with home assistant, since SolarEdge can just handle one direct communication connection.

In the OpenWB forums, I got the information, that it COULD be possible, to do the following:
1. disconnect the communication between openWB and SolarEdge Inverter
2. Get the information from the Inverter with Modbus, to have them in HomeAssistant
3. Send the required information throught MQTT to the OpenWB

I don't know, if this might already be possible with your great integration, but if not - would it be an Idea to implement such an option as well?
Maybe, this could be done within the configuration of your integration, f.e. that you can select the sensors that should provide these kind of information to the openWB... ?

Or do you have ideas how I could acheive such a configuration within HomeAssistant?
Thanks a lot and with best regards,
Christoph

**Comment by a529987659852** [comment]
Hi Christoph,

if I've understood correctly, your inverter is already connected to the
openWB and both are exchanging information.
If this is the case, I would recommend to check the MQTT messages on topic
openWB/pv/.
For me - I have a Fronius inverter - the data supplied from the inverter to
the openWB is already there. If this is the case, it is easy for me to add
additional sensors into my integration to display these values.

If you want to follow your approach, you can have modbus sensors in HA and
publish these values to MQTT. However, I doubt that this would help since
openWB would have to know what to do with these values.
Furthermore, I won't program such a functionality into my integration since
the main purpose is to display data from the openWB and control it.

Andreas

Am Fr., 20. Mai 2022 um 10:01 Uhr schrieb Christoph <
***@***.***>:

**Comment by ChristophCaina** [comment]
Hi Andreas,
thanks for your reply :)

yes, openWB and the Inverter are exchanging their information.

I've checked the MQTT messages you've mentioned with MQTTExplorer:
there are some information available, but not all that I can get from the SolarEdge Modbus Integration ...

I've taken a Screenshot of the topics / messages I think they might be relevant - and at the moment I can't really interpret the different values in detail... 
![grafik](https://user-images.githubusercontent.com/26391061/169489238-1d8659cb-accd-4378-9ea2-9650b5ae0a5c.png)

Unfortunately, the Modbus communication with the Inverter does also provide the information about the Inverter Status (running, sleeping, error, etc.) which I had in my dashboard.

At the moment, I am using the SolarEdge integration, which does call the information from the API - which is working, but just updating in 15min intervall - and not a "live" monitoring... and, I had some issues with this kind of integration in the past (in case of a missing internet connection or if the monitoring servers from solar edge were not available).

Anyway - thank you for your response :)
It's really a mess, that SolarEdge can't have multiple connections to their Interface... :-/
