### ISSUE TITLE
Multiple Standalone Wallboxes

### ISSUE THREAD

**Issue by UU0113** [a529987659852/openwbmqtt#43]
Hello,

I've 2 standalone Wallboxes which are not linked for reasons I want to add to Home Assistant. I tried to added the second one by simply creating another connection in mosquitto.conf but it does not seem to work.

Can you help?

**Comment by a529987659852** [comment]
Hi,
I never tested this since I only have one WB. However, this should work.
In the MQTT server which is connected to HA, create a bridge to the MQTT server of the 1st and 2nd wallbox. For each bridge, you should configure a seperate prefix. 

When adding the openWB integration in HA, the configuration dialogue asks for a prefix --> enter it here.

For more information regarding mosquitto bridge, please refer to this excellent guide:
http://www.steves-internet-guide.com/mosquitto-bridge-configuration/
topic topic pattern direction QOS **local prefix**

Andreas

**Comment by UU0113** [comment]
Thanks. Got it working after a while. 
For the reference:

`
#
# bridge to openWB Wallbox
#
connection openwb
address openwb.fritz.box:1883
start_type automatic
topic # in 0 openWB/ openWB/
local_clientid openwb.mosquitto
remote_clientid openwb.core-mosquitto
try_private false
cleansession false
keepalive_interval 5
allow_anonymous true

connection openwb2
address openwb2.fritz.box:1883
start_type automatic
topic # in 0 openWB2/ openWB/
local_clientid openwb2.mosquitto
remote_clientid openwb2.core-mosquitto
try_private false
cleansession false
keepalive_interval 5
allow_anonymous true
`

Please not it's readonly for HA.
In case you need, replace the word "in" with "both"...
