### ISSUE TITLE
How to use the "hidden" entities

### ISSUE THREAD

**Issue by n3de** [a529987659852/openwbmqtt#58]
Hey,
I'm using a mosquitto server to get the openwb data to home assistant. It works, but there are a few entities which are not used
![image](https://github.com/a529987659852/openwbmqtt/assets/81101039/1341190d-d002-4163-b08d-951942f40d72)
![image](https://github.com/a529987659852/openwbmqtt/assets/81101039/100464ca-5518-4ea9-a21b-515272d4af7d)
Why are these entities unabvailible and how can I use them?

**Comment by ChristophCaina** [comment]
you can enable them by klicking on the entity, then go to the cogwheel:
![grafik](https://github.com/a529987659852/openwbmqtt/assets/26391061/cce7943a-d6df-4c9c-8664-5a8137a6130c)

and then "enable" them.
![grafik](https://github.com/a529987659852/openwbmqtt/assets/26391061/5c72fc84-5b3a-4a82-b44e-f3686285efe1)

They are hidden, since those entities are not relevant for other people, if they have implemented batterie and measurements from other systems, like solaredge, etc.

**Comment by n3de** [comment]
Thank you very much for the fast response and help.

**Comment by ChristophCaina** [comment]
pls. consider to close the issue if it is solved.
Thank you
